### PR TITLE
SDK-1438: Update php version in CI

### PR DESCRIPTION
**Pull request by vol4onok**
https://spryker.atlassian.net/browse/SDK-1438

### CODE REVIEW

**Comment by dereuromark** [comment]
> Error: Call to function property_exists() with PhpParser\Node\Expr and 'class' will always evaluate to false.
Error: Call to function property_exists() with PhpParser\Node and 'stmts' will always evaluate to false.

Looks like PHPStan/code needs some fixing?

**Comment by vol4onok** [comment]
Let's pospone with update. needs to wait new phpstan version

**Comment by dereuromark** [comment]
You could also whitelist this issue, if the code is not at fault, and PHPStan needs a fix.

**Comment by dereuromark** [comment]
Did you open a ticket with PHPStan for this?

**Comment by vol4onok** [comment]
https://github.com/phpstan/phpstan/issues/8474

**Comment by vol4onok** [comment]
We support 7.4 and will have the issue there if I ignore it. because in 7.4 everything is ok

**Comment by DmytroKlymanSpryker** [comment]
Updated status: The issue with PHPStan is still relevant and has not been solved in PHPStan version 1.9.11.

**Comment by dereuromark** [comment]
Just baseline it

**Comment by DmytroKlymanSpryker** [comment]
> [phpstan/phpstan#8474](https://github.com/phpstan/phpstan/issues/8474)

issue is fixed

**Review by DmytroKlymanSpryker — APPROVED** [review]

**Pull request merged**
