### PR TITLE
Add code coverage badge

### PR DESCRIPTION
**Pull request by DmytroKlymanSpryker**
Add code coverage badge to README.md

### CODE REVIEW

**Review by dereuromark — APPROVED** [review]
But why does the badge need a token for a public repo?

**Comment by DmytroKlymanSpryker** [comment]
> But why does the badge need a token for a public repo?

That's a link that codedev generated for the project badge. They have 'token' parameter inside the link for all other public repositories as well

**Comment by dereuromark** [comment]
It seems there is no report uploaded yet, though for CI runs.

**Comment by DmytroKlymanSpryker** [comment]
> It seems there is no report uploaded yet, though for CI runs.

Upload exists in branch only, so it worked for the branch only, I checked it. After merge to the master it will work for master also and badge should appear with correct data.

**Comment by dereuromark** [comment]
You need to exclude files like

    src/Transfer/
    
paths

**Comment by DmytroKlymanSpryker** [comment]
For that <exclude> section (https://phpunit.readthedocs.io/en/9.5/configuration.html#the-exclude-element) should be just added after <include> (https://github.com/spryker-sdk/integrator/blob/master/phpunit.xml.dist#L6)

If you can provide the list of directories that should be excluded from code coverage, I'll exclude them in a minute.

**Comment by dereuromark** [comment]
Transfers arent real code, right, only "generated" once.
I dont think there are any other paths here.

**Comment by DmytroKlymanSpryker** [comment]
no, classes in src/Transfer in this project are not autogenerated. Project doesn't contain the .xml files for them

**Pull request merged**
